CREATE TABLE collisions(
  index BIGINT
  Borough TEXT,
  Contributing_Factor_1 TEXT,
  Contributing_Factor_2 TEXT,
  Contributing_Factor_3 TEXT,
  Contributing_Factor_4 TEXT,
  Contributing_Factor_5 TEXT,
  Cross_Street_Name TEXT,
  Date DATE,
  Latitude double precision,
  Longitude double precision,
  Number_of_Cyclist_Injured BIGINT,
  Number_of_Cyclist_Killed  BIGINT,
  Number_of_Motorist_Injured  BIGINT,
  Number_of_Motorist_Killed BIGINT,
  Number_of_Pedestrians_Injured BIGINT,
  Number_of_Pedestrians_Killed  BIGINT,
  Number_of_Persons_Injured BIGINT,
  Number_of_Persons_Killed  BIGINT,
  Off_Street_Name TEXT,
  On_Street_Name  TEXT,
  Time  TIME,
  Unique_Key  BIGINT NOT NULL UNIQUE,
  Vehicle_Type_Code1  TEXT,
  Vehicle_Type_Code2  TEXT,
  Vehicle_Type_Code3  TEXT,
  Vehicle_Type_Code4  TEXT,
  Vehicle_Type_Code5  TEXT,
  Zip_Code  BIGINT
);